alter session set "_ORACLE_SCRIPT" = true;
CREATE USER helpdesk IDENTIFIED BY "H3lpD3sk";
GRANT CREATE SESSION TO helpdesk;
GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE PROCEDURE TO helpdesk;
ALTER USER helpdesk QUOTA UNLIMITED ON USERS;